### ISSUE TITLE
Theme broken in Notepad 8.8.9

### ISSUE THREAD

**Issue by markvvaals** [dracula/notepad-plus-plus#69]
Seems the theme files have changed from 8.8.8 to 8.8.9 as updating to that version, there are more options to set colors for different parts of the editor and file content. This sadly, had broken Dracula themes in Notepad++ somewhat.
A few things I've noticed:

- The commented out field are very dark
<img width="724" height="165" alt="Image" src="https://github.com/user-attachments/assets/a3f83feb-ff77-48a9-bfb8-5df63f35e60c" />

- Some fields are formatted with a background color (ini file here)
<img width="562" height="205" alt="Image" src="https://github.com/user-attachments/assets/c4099389-4e71-4b1c-9969-64066e5157a8" />

- Inactive tabs are hard to read (dark text on dark background)
<img width="468" height="194" alt="Image" src="https://github.com/user-attachments/assets/c8c261cc-fdc4-493d-aada-b84ed181b206" />

The official theme files were also broken it seems, here someone explains that the theme files on the official Github have now been updated and seem to work properly again: https://community.notepad-plus-plus.org/topic/27305/theme-busted

P.S.
There seems to be a new way the zip file here is created (with .ts files in themes folder) so now the theme file you need to use is in the Generated folder. Would be good if this was added to the explanation on how to install these files [here](https://draculatheme.com/notepad-plus-plus).

**Comment by JGMelon22** [comment]
The issue persist at Notepad++ 8.9 as well :(

**Comment by SamKr** [comment]
Same, would be great if you could take a look @luxonauta

**Comment by luxonauta** [comment]
Hey — I pushed some updates that might fix this. Could you try the latest version and see if the issue is gone for you? 😊

**Comment by JGMelon22** [comment]
All looking great, man. Thank you so much <3
> Windows 11:
<img width="1365" height="767" alt="Image" src="https://github.com/user-attachments/assets/9d656b0c-bcf7-448b-a419-cf493b264348" />

> Arch Linux via Bottles:
<img width="2560" height="1044" alt="Image" src="https://github.com/user-attachments/assets/31ca301d-ccfe-4a8b-a608-7e98fe03d4cc" />

**Comment by markvvaals** [comment]
Thanks for diving into this @luxonauta 
It looks great now.

Only one issue remains: there is almost no contrast between the current line highlight and any selected text.

**Selection within a tag**
This is especially prevelant when selecting values _within a tag_ (since those are already auto highlighted when the tag is selected or you're inside the tag).
This is shown here, where I cannot see what I've selected even when zooming in to the screenshot.

<img width="1149" height="106" alt="Image" src="https://github.com/user-attachments/assets/84d546d6-6441-4884-8184-39beb9fcee8d" />
<details>
  <summary>Spoiler: the selected text</summary>
  
  `bgColor="282A36"`
  
</details>

**Selection in regular text**
This also applies to regular text (or anywhere that is not auto highlighted like non-syntax comments).
This is show here, in this scenario there is _a little_ contrast but not enough.

<img width="1149" height="44" alt="Image" src="https://github.com/user-attachments/assets/3c4b8a39-f1f7-464f-a1d3-f72d4b1f32cd" />

<details>
  <summary>Spoiler: the selected text</summary>
  
  `with all languages`

</details>


This issue is gets in the way for everyday use, since it should be very clear at a glance what you have selected.
Maybe this can be addressed by darkening the current line selection and auto-highlighting colors?

Thanks again for the work you put in.


### EDIT (addition):

Have been messing around a bit with the hex values within the GlobalStyles part of the Dracula.xml file.
Darkening the `Current line background colour` value of `bgColor="3E4152"` by about 15% (using [this site](https://mdigi.tools/darken-color/#3e4152)) is as low as I'd go to keep decent contrast between the normal background and selected line background, that gives me #353746.

Lightening the `Selected text colour` could also help, for instance 3E4152 + 15% gives me #565a71 which does help quite a bit functionally. But preferably highlights can stay aren't this bright as it doesn't look great.

However I cannot find what changes the color of the tags and the values within (of the XML in this case). I got the hex code with a color picker, but cannot find that value in the XML file.
If those could be darkened then I think the contrast should be there in the scenario's that I've found are problematic now.

**Comment by luxonauta** [comment]
I pushed some updates that might fix this. Could you try the latest version?

**Comment by markvvaals** [comment]
@luxonauta 
Thanks for the work!

---

The active line color is much better. Also the selection in regular text (or comments) is perfect.

<img width="1149" height="75" alt="Image" src="https://github.com/user-attachments/assets/6465fb36-2f50-4e8f-9bb1-6fea0fcd06d6" />

---

Two things when selecting things within a element:

1. The auto coloring of the attributes (name="..." styleID="..." etc.)
This is still a bit bright, so there is not a lot of contrast with the selected text
2. The element isn't colored anymore
In previous version these were colored (avocado like color) which wasn't a great color IMHO (should be somewhat darker and more color contrast with element text color that is pinkish red) but it was good to see where an element starts and ends (for elements with many attributes.
However in this version these are not colored at all anymore. Can you bring this back, maybe in a nicer color?

<img width="1149" height="109" alt="Image" src="https://github.com/user-attachments/assets/7aaea17f-ceed-465f-b67e-49f378897420" />

**Comment by luxonauta** [comment]
Hey I just pushed some more updates that might fix this. Could you try again, with the latest version? 😊

**Comment by markvvaals** [comment]
@luxonauta 
This change has made the attribute text color much darker (name="..." styleID="..." etc.)
Reading my previous comment, I was not clear. With auto-coloring I meant the _background color_, not the text color.

The attribute _text_ color was better before, being bright blue.
I would suggest, reverting that change and making the attribute background color darker.
Maybe change Tags attribute to bgColor="666b8a", that seems to be a nice balance of clarity but not intrusive, if you find it too much then darkening it a little bit is also an option.

Regarding my previous point #2 (element color) this seems to be "Tags match highlighting" which was bgColor="F1FA8C" and now is  bgColor="45465D" that is so dark it's not noticeable. This should be clear as well. The previous color was fine for clarity but doesn't really match Dracula theme colors. So reverting this or finding a better, brighter color is preferable.

**Comment by luxonauta** [comment]
I pushed more updates that might fix this. Could you try the latest version and see if the issue is gone for you? 😊

**Comment by markvvaals** [comment]
@luxonauta thanks again. This looks good, thank you very much!

**Comment by markvvaals** [comment]
@luxonauta I just found another bug that I missed before. When selecting a word, other instances of the same word aren't (visibly) highlighted.

This is controlled by `Smart HighLighting` which now has `bgColor="353746"` which is too dark.
A much older version of the Dracula.xml file had `Smart HighLighting` as `bgColor="8BE9FD"` which works well in all instances I've tried. So if you could change `Smart HighLighting` to `bgColor="8BE9FD"` that would be great.

**Comment by luxonauta** [comment]
Just pushed an update, Mark - can you take another look?

> I'll go ahead and close this issue; feel free to open a new one so we don't lose context as the thread grows. 😊
